---
title: "TestModelsByQB"
author: "Zach Feldman"
date: "3/4/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(broom)
library(tidyverse)
library(knitr)
```

Test XGBoost, GAM, Air Yards only GAM
```{r}
plays_qb_test <- cpoe_passes %>% select(season, passer_player_name, complete_pass)
```

Add prediction columns
```{r}
plays_qb_test$xgboost_pred <- xgb_mod_full_pred
plays_qb_test$gam_pred <- gam_pred_full
plays_qb_test$gam_air_pred <- gam_pred_air_full
```

Add cpoe columns
```{r}
plays_qb_test %<>% mutate(cpoe_xgb = complete_pass - xgboost_pred,
                          cpoe_gam = complete_pass - gam_pred,
                          cpoe_air = complete_pass - gam_air_pred)

```

Group by season and qb
```{r}
cpoe_by_season <- plays_qb_test %>% group_by(passer_player_name, season) %>% 
  summarise(attempts = n(),
            cpoe_sum_xgb_season = sum(cpoe_xgb),
            cpoe_sum_gam_season = sum(cpoe_gam),
            cpoe_sum_air_season = sum(cpoe_air),
            
            cpoe_mean_xgb_season = mean(cpoe_xgb),
            cpoe_mean_gam_season = mean(cpoe_gam),
            cpoe_mean_air_season = mean(cpoe_air))
  
```

Test year over year with map
```{r}
yoy_model <- function(cpoe, df) {
  lm(data = df, formula = cpoe ~ lag(cpoe), na.action = na.omit) %>% glance() %>%
    select(r.squared) %>% as.numeric()
}

min_attempts <- 320

cpoe_by_season %>% 
  filter(attempts >= min_attempts) %>% 
  group_by(passer_player_name, season) %>% 
  arrange(passer_player_name, season) %>% 
  map_at(vars(contains("cpoe")), .f = yoy_model)

cpoe_by_season %>% filter(attempts >= min_attempts) %>% 
  group_by(passer_player_name, season) %>% 
  arrange(passer_player_name, season) %>%
  map_at(vars(contains("cpoe")), .f = ~cor(., lag(.), use = "na.or.complete"))
```


Test against 2019 data
```{r}
test_19 <- cpoe_19_passes %>% select(complete_pass, air_yards, yardline_100, ydstogo, receiver_position, 
         down, qtr, wp, ep, air_is_zero, pass_is_middle, under_two_min,
         tipped, hail_mary, roof, posteam_type, week, season, qb_hit, shotgun, no_huddle, goal_to_go)

test_19 %<>% modify_if(is_character, as_factor)

test_19_dmatrix <- xgb.DMatrix(model.matrix(~.+0, data = test_19 %>% select(-complete_pass)), label = test_19$complete_pass)
dimnames(test_19_dmatrix) <- dimnames(full_train)
test_19$xgb <- predict(xgb_mod_full, test_19_dmatrix)
test_19$gam <- predict.bam(gam_full, test_19 %>% select(-xgb), type = "response")
test_19$air <- predict.bam(gam_air_full, test_19 %>% select(-xgb, -gam), type = "response")

test_19 %<>% mutate(xgb_error = complete_pass - xgb,
                    gam_error = complete_pass - gam,
                    air_error = complete_pass - air)

test_19 %>% summarise(xgb_mse = round(mean(xgb_error^2), 4),
                      gam_mse = round(mean(gam_error^2), 4),
                      air_mse = round(mean(air_error^2), 4))
```




```{r}
results <- matrix(c(.201, .202, .119, .194, 
                    .204, .203, .101, .196, 
                    .214, .212, .115, .206), ncol = 4, byrow = TRUE)
colnames(results) <- c("Full In Sample MSE", "30% Out of Sample MSE", "QB CPOE YoY R^2", "Test 2019 MSE")
rownames(results) <- c("XGBoost", "GAM", "Air Yards Only - GAM")
kable(results)
```


Test Exp Comp (cp) and CPOE by receiver
```{r}
plays_receiver_test <- cpoe_passes %>% select(receiver_player_id, season, cp, cpoe, air_yards, receiver_position) %>% filter(receiver_position %in% c("TE", "WR"))

receiver_cpoe_by_season <- plays_receiver_test %>% group_by(receiver_player_id, season) %>% 
  summarise(targets = n(),
            cpoe_mean = mean(cpoe),
            exp_comp_mean = mean(cp),
            
            cayoe_mean = mean(cpoe * air_yards),
            exp_ay_mean = mean(cp * air_yards))

min_targets <- 43

receiver_cpoe_by_season %>% 
  filter(targets > min_targets) %>% 
  group_by(receiver_player_id, season) %>% 
  arrange(receiver_player_id, season) %>% 
  map_at(vars(contains("mean")), .f = yoy_model)


```


```{r}
plays_quarterback_test <- cpoe_passes %>% select(passer_player_id, season, cp, cpoe, air_yards)

quarterback_cpoe_by_season <- plays_quarterback_test %>% group_by(passer_player_id, season) %>% 
  summarise(attempts = n(),
            cpoe_mean = mean(cpoe),
            exp_comp_mean = mean(cp),
            
            cayoe_mean = mean(cpoe * air_yards),
            exp_ay_mean = mean(cp * air_yards))

min_attempts <- 128

quarterback_cpoe_by_season %>% 
  filter(attempts > min_attempts) %>% 
  group_by(passer_player_id, season) %>% 
  arrange(passer_player_id, season) %>% 
  map_at(vars(contains("mean")), .f = yoy_model)
```


```{r}
plays_defensive_test <- cpoe_passes %>% select(defteam, season, cp, cpoe, air_yards)

defensive_cpoe_by_season <- plays_defensive_test %>% group_by(defteam, season) %>% 
  summarise(cpoe_mean = mean(cpoe),
            exp_comp_mean = mean(cp),
            
            cayoe_mean = mean(cpoe * air_yards),
            exp_ay_mean = mean(cp * air_yards))


defensive_cpoe_by_season %>% 
  group_by(defteam, season) %>% 
  arrange(defteam, season) %>% 
  map_at(vars(contains("mean")), .f = yoy_model)
```


```{r}
plays_coach_test <- cpoe_passes %>% mutate(posteam_coach = if_else(posteam_type == "away", away_coach, home_coach)) %>% select(posteam_coach, season, cp, cpoe, air_yards)

coach_cpoe_by_season <- plays_coach_test %>% group_by(posteam_coach, season) %>% 
  summarise(cpoe_mean = mean(cpoe),
            exp_comp_mean = mean(cp),
            
            cayoe_mean = mean(cpoe * air_yards),
            exp_ay_mean = mean(cp * air_yards))


coach_cpoe_by_season %>% 
  group_by(posteam_coach, season) %>% 
  arrange(posteam_coach, season) %>% 
  map_at(vars(contains("mean")), .f = yoy_model)
```

